server:
  port: 8081

spring:
  application:
    name: van
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  batch:
    jdbc:
      initialize-schema: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    enabled: true
  instance:
    prefer-ip-address: true

batch:
  csv:
    path: ./csv/
  gateway:
    url: http://localhost:8080/api/settlement/upload

logging:
  level:
    org.springframework.batch: DEBUG